name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install root deps
        run: npm ci

      - name: Build TheGames subproject
        working-directory: TheGames
        env:
          # Optional: set VITE_BASE in repository secrets if serving under /<repo>/
          VITE_BASE: ${{ secrets.VITE_BASE }}
        run: |
          npm ci
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TheGames/dist
          # optional: keep docs or other settings here
