name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install root deps
        run: npm ci

      - name: Ensure VITE_BASE is set
        # If the VITE_BASE secret is not provided, compute it from the repo name: '/<repo>/'
        run: |
          if [ -z "${{ secrets.VITE_BASE }}" ]; then
            echo "VITE_BASE=/${{ github.event.repository.name }}/" >> $GITHUB_ENV
            echo "Computed VITE_BASE=/${{ github.event.repository.name }}/"
          else
            echo "VITE_BASE=${{ secrets.VITE_BASE }}" >> $GITHUB_ENV
            echo "Using provided VITE_BASE"
          fi

      - name: Build TheGames subproject
        working-directory: TheGames
        # Use the VITE_BASE value from the environment (set earlier via $GITHUB_ENV)
        env:
          VITE_BASE: ${{ env.VITE_BASE }}
        run: |
          npm ci
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Use a personal access token if provided (PAGES_PAT), otherwise fall back to the default GITHUB_TOKEN
          github_token: ${{ secrets.PAGES_PAT || secrets.GITHUB_TOKEN }}
          publish_dir: ./TheGames/dist
          # optional: keep docs or other settings here
